### ISSUE TITLE
Optimization is too slow

### ISSUE THREAD

**Issue by achilles1989** [dportik/dadi_pipeline#13]
Thanks a lot for this useful tool which makes dadi much more convenient to use.

I used EasySFS.py to make a folded frequency spectrum of about 600,000 SNPs and wanted to use dadi-pipeline to inference the demographic history. While I stuck in the optimization step and almost no result came out after two days. I don't understand why this problem occurs, because the number of SNPs used in many papers is always greater than 1,000,000. Or is this an acceptable speed?

```
import dadi
import numpy
import Optimize_Functions

path_sfs = 'HANN-HANS-TIB.sfs'
fs = dadi.Spectrum.from_file(path_sfs)

from Three_Population_Pipeline.Models_3D import split_nomig

prefix = "V1"

pts_l = [180,190,200]
p_labels = 'nu1, nuA, nu2, nu3, T1, T2'
reps = [10, 10, 10]
maxiters = [5, 5, 5]
folds = [3, 2, 1]
Optimize_Functions.Optimize_Routine(fs=fs, 
                                    pts=pts_l, 
                                    outfile=prefix, 
                                    model_name="split_nomig", 
                                    func=split_nomig, 
                                    rounds=3, 
                                    param_number=6, 
                                    fs_folded=True, 
                                    param_labels=p_labels,
                                    optimizer="log",
                                    reps=reps,
                                    maxiters=maxiters,
                                    folds=folds)
```
[HANN-HANS-TIB.sfs.zip](https://github.com/dportik/dadi_pipeline/files/4168719/HANN-HANS-TIB.sfs.zip)

**Comment by dportik** [comment]
Hello,
It seems that this is not a dadi-pipeline issue, but more related to how dadi works. The slowness is likely a consequence of fitting a 3D model (they alway takes longer than a 2D model), with perhaps a large sample size and grid size. How many samples are included in each population? If there are many, it will go slower. Judging by the grid size you've selected, there may be many samples. The number of SNPS should not be an issue. 

You may choose to fit simpler 2D models first to understand the potential histories of the pairwise populations, then target a small number of 3D models. It will still be slow to fit those 3D models, but you won't have to do as much model testing.
