### ISSUE TITLE
Question about input file

### ISSUE THREAD

**Issue by jingfangG** [dportik/dadi_pipeline#14]
Dear Mr.Daniel,
Thank you for providing such a good pipeline! I'm trying to run a 2D model, but I have a problem. If I already have an SFS file, how do I modify the script "dadi_Run_2D_Set.py". I defined "fs" directly as my SFS file, but I found this didn't work. 

Thanks,
Jing-fang Guo

**Comment by dportik** [comment]
Hello Jing-fang,
I am glad you have found this pipeline useful! 

Regarding your question, have you referenced the manual for dadi? It looks like a solution is to import the SFS file directly using the following:
```
fs = dadi.Spectrum.from_file(filename)
```
Where `filename` is the full path to your file. Please let me know if this works for your case.

**Comment by jingfangG** [comment]
Dear Mr.Daniel,
Thank you very much for helping me solve the problem. I have started to run the 2D model smoothly.
Best,
Jing-fang Guo
