### ISSUE TITLE
How to transform the parameter to true  parameter

### ISSUE THREAD

**Issue by pengyan19** [dportik/dadi_pipeline#19]
For example, we used the admix_origin_no_mig model in 3 population, but i got the best AIC result which is  [4.3764,4.0015,1.4507,0.0146,0.0117,1.3506],["nu1, nu2, nu3, T1, T2 , f"), why the f >0? and how did the T1,T2  transform to  true time?

**Comment by dportik** [comment]
Hi @pengyan19,
It looks like the upper bound and starting parameters were missing from these models. The f parameter needs to be bounded between 0 and 1 for the model to make sense. I added in the appropriate bounds in the `dadi_Run_3D_Set.py` script. If you download the updated version, you will need to re-run the admixture models using these updated settings. Apologies for any inconvenience, and thanks for posting this issue.

For transformations to true time and other parameters, please consult the dadi manual and the dadi user group.
