### ISSUE TITLE
about asymmetric migration and adjiacent asymmetric migration models

### ISSUE THREAD

**Issue by XuexueLiu** [dportik/dadi_pipeline#2]
Dear dportik
I have used dadi for a long time, now I used three populations to calculate the best models, now I need Divergende, asymmetric migration and Divergence adjacent asymmetric migration models, that were not concluded in the script. you can send to my Email:lxx_caas@163.com. Thankyou!

 And another problem, I have encountered is that, when Round1 finished I get several tables. should I choose the maximum log-likelyhood or the minimum ones for the parameter to use. For example,

Model | param_set | Replicate | log-likelihood | theta | AIC | optimized_params |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Refugia 2 with secondary contact | parameter set = [nu1, nuA, nu2, nu3, m1, m2, T1, T2] | 18 | -64414289 | 711737.1 | 1.29E+08 | 1.2559 | 0.6359 | 6.987 | 0.1385 | 0.0677 | 9.1648 | 7.3236 | 0.1197
Refugia 2 with secondary contact | parameter set = [nu1, nuA, nu2, nu3, m1, m2, T1, T2] | 46 | -19011234 | 526348.7 | 38022484 | 1.3546 | 2.3947 | 29.5382 | 0.8774 | 0.3592 | 19.6276 | 4.8849 | 0.6666

which line I should choose, Thanyou !

**Comment by dportik** [comment]
Hello,
I have recently re-written the pipeline to make analyzing custom models much easier. I will be adding the 3D model set soon, but in the mean time I encourage you to write the model function and analyze it using the new script. 

Looking at your log-likelihood scores, they appear to be quite bad. Are you sure you are using dadi correctly? There may be a problem with your data, the model use, or other issues. Without knowing anything about your input data, this is unclear.

**Comment by dportik** [comment]
The new 3D model set has been updated and added. I should mention that the 3D models you are referring to were not actually implemented in the previous pipeline - I had thought about fitting them but testing showed they ran very slowly and tended to not converge well. You can write your own model functions and use the general use script at https://github.com/dportik/dadi_pipeline/ to fit them if you'd like. I will be adding more 3D models soon but they will only include symmetric migration to simplify the models.
