### ISSUE TITLE
Default parameter boundaries

### ISSUE THREAD

**Issue by joannarifkin** [dportik/dadi_pipeline#6]
Hi Dan,

I have another question. If I don't set the optional bounds on the parameters, what are the bounds for them? Can I look for behavior like parameters that chase the upper/lower bound? Or are they able to take any value?

Thanks,

Joanna

**Comment by dportik** [comment]
Hi Joanna,
If no parameter bounds are specified the upper and lower bounds will be automatically generated with values of 30 and 0.01, respectively. The starting parameter values for the first round of optimizations are always 1, but they are perturbed three-fold (using the folds argument) to create a different randomized starting set for each of the searches in the first round. In a given model with 5 parameters, this would be represented as:

upper = [30, 30, 30, 30, 30]
lower = [0.01, 0.01, 0.01, 0.01, 0.01]
starting params = [1, 1, 1, 1, 1]

If you are concerned about parameter values hitting the bounds, check to see if the values are very close to 30 or 0.01. If so, then the limits are being reached and you should decide whether to supply your own custom bounds instead, and what those should look like. Hope this helps!

**Comment by joannarifkin** [comment]
Hi Dan,

Great! I wanted to check because I'm using linked SNPs and therefore planning to compare models with based on bootstrapped data. Apparently parameters that are close to the bounds are problematic for the null distribution of the Godambe Information Matrix (companion post here: https://groups.google.com/forum/#!topic/dadi-user/kSAhZ5OvN54). None of the parameters that differ between the models I'm looking at are anywhere near the bounds, though, so it's all good! (All the models agree that there's asymmetric migration, but it's less clear whether there were periods of no migration and whether the populations changed size.)

Thank you again for being so responsive (and for the wrapper/pipeline, it's been very helpful)!

Cheers,

Joanna
