### ISSUE TITLE
running time

### ISSUE THREAD

**Issue by XuexueLiu** [dportik/dadi_pipeline#7]
I used dadi to run the asymigration model of three populations, it last for a week, but only go to Round 2 , are there any ways to speed up. I tried to use  more threads, but failed. Thankyou!

**Comment by dportik** [comment]
The 3D models which contain many parameters will take much longer to fit. This is why I used 3D models with symmetric migration only. If you with to speed up the runs, you can change a few options. Reducing the number of replicates will speed up the pipeline. You can also change the maxiter arguments (lowering the number), but this will come at the cost of less thorough searches.

If you wish to finish the pipeline if you are on round two, you may inspect the output files and find the best-scoring replicate so far and use the parameters as the starting set, and simply run the settings to complete the final round. For example:

`#change number of rounds to 1, change other relevant arguments too
rounds = 1
reps = [30] #or whatever number of replicates you want
maxiters = [15] #or lower if taking too long
folds = [1]

#example of input parameters for a model with 6 parameters, here use the values from the best replicate from rounds 3 and 2
best_params = [5,7,4,2,8,3]

#call the model you defined however you have it written, this is just an example
#you'll want to include the in_params argument to read in your starting parameter set
Optimize_Functions.Optimize_Routine(fs, pts, prefix, "your_model", Model_Function, rounds, 6, fs_folded=fs_folded, reps=reps, maxiters=maxiters, folds=folds, in_params=best_params)
`

No matter what approach you use, there is a trade-off between speed and accuracy. If you choose to alter the settings and find that the resulting log-likelihoods of your final replicates are not consistent, there is a strong change you have not yet found the optimum and you need to continue searches until they begin converging. This can take a lot of time for complex models, and you may not be able to take shortcuts to get there. Hope this helps.

**Comment by XuexueLiu** [comment]
it's very kind of you, I will consider this and thanks again for your help!

**Comment by SkyStarStear** [comment]
Dear XuexueLiu
 Hello，I have the same problem with you. And I‘d like to try to use threading or Multiprocessing(since I don't know which is avaliable for dadi) with 20 threads on Linux. And can you share your script with me.

**Comment by XuexueLiu** [comment]
I have no ides about the time, it did take a lot of time. No other ways to sove it, I have mailed to the author. 
Take care


------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年7月29日(星期一) 下午4:57
收件人: "dportik/dadi_pipeline"<dadi_pipeline@noreply.github.com>;
抄送: "Xuexue Liu"<767245705@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [dportik/dadi_pipeline] running time (#7)




Dear XuexueLiu
 Hello，I have the same problem with you. And I‘d like to try to use threading or Multiprocessing(since I don't know which is avaliable for dadi) with 20 threads on Linux. And can you share your script with me.
