### ISSUE TITLE
founder_nomig_admix_two_epoch model argument T2 not used

### ISSUE THREAD

**Issue by hemstrow** [dportik/dadi_pipeline#8]
On line 912 of Models_2D.py, the founder_nomig_admix_two_epoch model has:

phi = Integration.two_pops(phi, xx, T1, nu1, nu2, m12=0, m21=0)

I suspect it should instead read:

phi = Integration.two_pops(phi, xx, T2, nu1, nu2, m12=0, m21=0)

Since T2 is the time between the admixture event and the present. If I understand correctly, the model as it stands assumes equal time between the founding and admixture events and the admixture event and the present.

**Comment by dportik** [comment]
You are correct, this was supposed to include T2 rather than T1. This mistake has been fixed in the updated code. Thanks for taking the time to read through the models carefully enough to catch this issue!

**Comment by dportik** [comment]
@hemstrow I just wanted to follow up on this and report that there were other issues I found with the original island model set, including mis-assigned and nonsense parameters. These models were incorrectly specified in addition to the issue you raised.

I discussed some better approaches to these models with Ryan (threads [here](https://groups.google.com/g/dadi-user/c/9cP7JVRoVsg/m/SHE1_q38AQAJ) and [here](https://groups.google.com/g/dadi-user/c/mAcWgjMC-5k/m/_zg8uHZ_CAAJ)). Afterwards, I completely re-wrote the original island model set. I released the revised island models as part of dadi_pipeline [v3.1.1 ](https://github.com/dportik/dadi_pipeline/releases/tag/V3.1.1) in December 2019. 

I'm not sure if you have seen these updates, but wanted to make you aware of them. If you plan to use the revised island models, please let me know if you find any other issues or discrepancies. These resources are a work in progress, and I always appreciate the feedback.

Thanks!

**Comment by xuefenfei712** [comment]
Dear dportik

To continue this question, I want to build 1D model that my population experienced first bottleneck and then a founder effect, I draft the code, while it shows error:
code:
def three_epoch_founder(params, ns, pts):
    """
    params = (nuB,nuF,nuFd,TB,TF,TFe)
    ns = (n1,)

    nuB: Ratio of bottleneck population size to ancient pop size
    nuF: Ratio of contemporary to ancient pop size ##Ratio of founder to ancient
    nuFd: Ratio of contemporary to founder
    TB: Length of bottleneck (in units of 2*Na generations)
    TF: Time since bottleneck recovery (in units of 2*Na generations)
    TFe: Time of founder effect
    n1: Number of samples in resulting Spectrum
    pts: Number of grid points to use in integration.
    """
    nuB,nuF,nuFd,TB,TF,TFe = params

    xx = Numerics.default_grid(pts)
    phi = PhiManip.phi_1D(xx)

    phi = Integration.one_pop(phi, xx, TB, nuB)
    phi = Integration.one_pop(phi, xx, TF, nuF)
    nuFd_func = lambda t: nuF * (nuFd/nuF)**(t/TFe)
    phi = Integration.one_pop(phi, xx, TFe, nuFd=nuFd_func)
    fs = Spectrum.from_phi(phi, ns, (xx,))
    return fs
three_epoch_founder.__param_names__ = ['nuB', 'nuF','nuFd', 'TB', 'TF', 'TFe']

Looking forward for your reply, thankyou
Best
Xue

**Comment by dportik** [comment]
Hi @xuefenfei712 ,
For questions related to model specification (and not the pipeline workflow), please post on the dadi user group:
https://groups.google.com/g/dadi-user
